// Local Q&A pairs for VerseIQ Support Agent
export interface FaqPair {
  q: string;
  a: string;
}

export const FAQ_PAIRS: FaqPair[] = [
  { q: "Why does it say I’m getting streams but not getting paid", a: "That message means VerseIQ detected playback activity, but the metadata chain linking those streams to your rights is incomplete. It’s a signal of a gap, not confirmation of missing royalties." },
  { q: "What is a Coverage Score", a: "It’s a health indicator showing how complete and aligned your metadata and registrations appear across the value chain." },
  { q: "My score is 50. Is that bad", a: "It means your catalog has mixed alignment—some parts are clean, others need attention." },
  { q: "What does “Medium Signal” mean", a: "It means the track shows activity but the metadata is only partially aligned." },
  { q: "Why does it show Streams Tracked", a: "It reflects detected playback signals, not confirmed royalties." },
  { q: "Why is Missing ISRCs = 0 but I still have issues", a: "ISRCs are present, but other metadata or registrations may be incomplete." },
  { q: "What should I do first", a: "Start with the tracks flagged as active and incomplete." },
  { q: "Does VerseIQ confirm royalties", a: "No. It identifies metadata gaps and signals, not payouts." },
  { q: "Why are some tracks flagged", a: "They show activity but incomplete or conflicting metadata." },
  { q: "What does Platforms Scanned mean", a: "It shows how many platforms were included in your scan." },
  { q: "What’s the difference between ISRC and ISWC", a: "ISRC identifies the recording; ISWC identifies the composition." },
  { q: "Why do registrations matter", a: "Without them, royalties can’t be matched to your works." },
  { q: "What is a metadata conflict", a: "When two sources disagree about ownership, identifiers, or splits." },
  { q: "What is registration alignment", a: "It measures how well your metadata matches what rights organizations expect." },
  { q: "Why is my registration incomplete", a: "Missing splits, missing publishers, or mismatched identifiers." },
  { q: "What is a CMO", a: "A collective management organization that handles rights and royalties." },
  { q: "What is a PRO", a: "A performing rights organization that manages performance royalties." },
  { q: "What is SoundExchange", a: "It manages neighboring rights for performers and labels in the US." },
  { q: "Why do I need both ISRC and ISWC", a: "They connect the recording and composition sides of royalty flow." },
  { q: "What is DSP alignment", a: "Ensuring your metadata matches what streaming platforms use." },
  { q: "What does AI-assisted mean", a: "A human created the work with AI tools involved." },
  { q: "What does AI-generated mean", a: "The work was created primarily by an AI system." },
  { q: "Why is my AI risk high", a: "Missing provenance, unclear authorship, or incomplete disclosures." },
  { q: "What is derivative lineage", a: "It shows whether your work resembles or derives from other works." },
  { q: "Why does AI matter for royalties", a: "Some jurisdictions require disclosure of AI involvement." },
  { q: "What is provenance completeness", a: "How fully your AI involvement is documented." },
  { q: "What is a model ID", a: "The specific AI system used in creation." },
  { q: "Why is lineage unclear", a: "Missing source references or similarity signals." },
  { q: "Does AI-generated music get royalties", a: "Policies vary; VerseIQ doesn’t decide legal status." },
  { q: "What should I do if my AI attribution is incomplete", a: "Add missing model info, prompts, or human contribution details." },
  { q: "What is a Recovery Plan", a: "A structured set of actions to fix metadata and registration gaps." },
  { q: "What is a Recovery Token", a: "Authorization for VerseIQ to generate a correction package." },
  { q: "Does Recovery guarantee money", a: "No. It improves metadata alignment but doesn’t confirm payouts." },
  { q: "What should I fix first", a: "Tracks with activity + incomplete metadata." },
  { q: "How do I check my registrations", a: "Log into your PRO/CMO and verify each work." },
  { q: "What if my publisher handles this", a: "Share your scan results with them." },
  { q: "Should I contact my PRO", a: "Yes, if you see mismatches or missing works." },
  { q: "Should I contact my distributor", a: "Yes, if ISRCs or metadata are incorrect." },
  { q: "What if I don’t understand my scan", a: "Start with the high-level cards or ask for help here." },
  { q: "Should I run scans regularly", a: "Yes, especially after new releases or catalog updates." },
  { q: "Can you tell me if I’m owed royalties", a: "I can’t confirm payouts; I can help interpret signals." },
  { q: "Can you read my contract", a: "I can’t interpret contracts or give legal advice." },
  { q: "Can you tell me who made a mistake", a: "VerseIQ highlights gaps but doesn’t assign fault." },
  { q: "Can you calculate my royalties", a: "No. VerseIQ doesn’t access internal royalty statements." },
  { q: "Why can’t you confirm money", a: "VerseIQ uses metadata and signals, not financial reports." },
  { q: "Should I hire a lawyer", a: "I can’t advise on that; I can help clarify your data." },
  { q: "Why is my data inconsistent", a: "Metadata can break at many points in the chain." },
  { q: "Can you fix my registrations", a: "I can guide you, but updates must be submitted to rights orgs." },
  { q: "Can you contact my PRO", a: "No, but I can help you prepare what to send them." },
  { q: "What’s the most important thing to do", a: "Focus on active tracks with incomplete metadata." },
];
