"use client";

import { useMemo } from "react";
import { HeroCard } from "@/components/ai-attribution/HeroCard";
import { InvolvementCard } from "@/components/ai-attribution/breakdown/InvolvementCard";
import { LineageCard } from "@/components/ai-attribution/breakdown/LineageCard";
import { RegistrationAlignmentCard } from "@/components/ai-attribution/breakdown/RegistrationAlignmentCard";
import { AttributionMatrixCard } from "@/components/ai-attribution/detail/AttributionMatrixCard";
import { ProvenanceTimelineCard } from "@/components/ai-attribution/detail/ProvenanceTimelineCard";
import { RiskCard } from "@/components/ai-attribution/detail/RiskCard";
import { ConflictResolutionCard } from "@/components/ai-attribution/ConflictResolutionCard";
import { AuditModeCard } from "@/components/ai-attribution/AuditModeCard";

import type {
  AIAttributionSummary,
  AIInvolvement,
  DerivativeLineage,
  RegistrationAlignment,
  AttributionMatrix,
  ProvenanceEvent,
  RiskAssessment,
} from "@/types/aiAttribution";

// --- MOCK DATA ---
const summary: AIAttributionSummary = {
  attributionType: "AI-Assisted",
  provenanceCompleteness: 72,
  riskLevel: "medium",
};
const involvement: AIInvolvement = {
  detectedModels: ["ChatGPT", "Stable Diffusion"],
  humanContribution: 60,
  aiContribution: 40,
  confidenceScore: 88,
  missingDeclarations: ["Model ID"],
};
const lineage: DerivativeLineage = {
  sourceWorks: ["Classic Song A"],
  similarityIndicators: ["Melodic overlap"],
  derivativeRelationships: ["Remix"],
  jurisdictionRelevance: ["US", "EU"],
};
const alignment: RegistrationAlignment = {
  cmoSupport: false,
  conflicts: ["ISRC mismatch"],
  requiredCorrections: ["Add AI field to CMO"],
};
const matrix: AttributionMatrix = {
  human: [
    { nameOrModel: "Alice", contributionPercent: 50, confidence: 90, source: "manual" },
    { nameOrModel: "Bob", contributionPercent: 10, confidence: 80, source: "manual" },
    { nameOrModel: "-", contributionPercent: 0, confidence: 0, source: "manual" },
  ],
  ai: [
    { nameOrModel: "ChatGPT", contributionPercent: 20, confidence: 85, source: "inferred" },
    { nameOrModel: "Stable Diffusion", contributionPercent: 20, confidence: 80, source: "inferred" },
    { nameOrModel: "-", contributionPercent: 0, confidence: 0, source: "inferred" },
  ],
  hybrid: [
    { nameOrModel: "-", contributionPercent: 0, confidence: 0, source: "external" },
    { nameOrModel: "-", contributionPercent: 0, confidence: 0, source: "external" },
    { nameOrModel: "-", contributionPercent: 0, confidence: 0, source: "external" },
  ],
};
const events: ProvenanceEvent[] = [
  { timestamp: "2024-01-01", event: "Created", details: "Initial composition" },
  { timestamp: "2024-01-05", event: "AI Generation", details: "Lyrics generated by ChatGPT" },
  { timestamp: "2024-01-10", event: "Edit", details: "Melody revised by Alice" },
  { timestamp: "2024-02-01", event: "Registration", details: "Registered with CMO" },
];
const risk: RiskAssessment = {
  riskLevel: "medium",
  missingMetadata: ["Model ID", "AI field in CMO"],
  jurisdictionRequirements: ["EU: AI disclosure", "US: registration update"],
  recommendations: ["Add missing model info", "Update CMO registration"],
};

export default function AIAttributionPage() {
  return (
    <div className="p-6 space-y-6">
      <HeroCard summary={summary} onViewDetails={() => {}} />
      <div className="grid md:grid-cols-3 gap-4">
        <InvolvementCard involvement={involvement} />
        <LineageCard lineage={lineage} />
        <RegistrationAlignmentCard alignment={alignment} onGenerate={() => {}} />
      </div>
      <div className="space-y-4">
        <AttributionMatrixCard matrix={matrix} />
        <ProvenanceTimelineCard events={events} />
        <RiskCard risk={risk} />
        <ConflictResolutionCard verseiq="AI-Assisted, 40% AI, ISRC: 123" cmo="Human-Only, ISRC: 456" onGenerate={() => {}} />
        <AuditModeCard missingAI={2} derivativeAmbiguity={1} cmoConflicts={1} onReview={() => {}} />
      </div>
    </div>
  );
}
